### ISSUE TITLE
Handle count with s and S

### ISSUE THREAD

**Issue by occivink** [Delapouite/kakoune-auto-percent#2]
Currently the rebound s and S ignore the count parameter

**Comment by Delapouite** [comment]
Thanks.
I must admit I'm not very familiar with the arcane usage of count with `s` and `S`.
Without checking I thought that it will select the first `count` occurences, but in fact, it has to do with regex capture groups.

**Comment by occivink** [comment]
Yes it's very niche (less so in scripts), it took me a while to notice that remapping these keys would do that.
